### ISSUE TITLE
Weird Freezing Bug

### ISSUE THREAD

**Issue by abb3v** [KartoffelChipss/fzf-colorpicker#1]
There's this bug that i can't really explain without a video (provided), in essence, after messing around with the color selector, it randomly freezes and wont close.

https://github.com/user-attachments/assets/5f67f2ed-47bd-4087-99d0-d63cf1510006

As you can hopefully see here, the first two times i touch the color selectors, they work fine! Then the third time, it wont close...

**Comment by KartoffelChipss** [comment]
What browser are you using?

**Comment by abb3v** [comment]
Firefox. I'm not rich and can use safari on a macbook pro 17", 64GB RAM, 8 Trillion Euro machine.

But irrespective, when developing a web app you should ensure your CSS and other relative browser-specific code works seamlessly. You get a B- from me on this.

**Comment by KartoffelChipss** [comment]
I found the error and it has nothing to do with css. I'll fix it as soon as possible.
